// rafce
'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/views/layout/Footer'
import Header from '@/views/layout/Header'
import FooterBar from '@/views/layout/FooterBar'
import Providers from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.PromiseLikeOfReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Header />
        <main className='px-8'>
         {children}
        </main>
       { /* < Footer />  */}
       <Footer />
       { /* <FooterBar />  */}
       <FooterBar />
       </Providers>   
        </body>
    </html> 
     )
};
