import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/views/layout/Header'
import Footer from '@/views/layout/Footer'
import FooterBar from '@/views/layout/FooterBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`max-w-[1440px] mx-auto ${inter.className}`}>
        <Header />
        <main className='px-16'>
            {children}
        </main>
        <Footer />
        <FooterBar />
        </body>
    </html>
  )
}
